apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: retail-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carts
  namespace: retail-app
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: dynamodb
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: project-bedrock-carts
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "false"
  AWS_REGION: us-east-1
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: retail-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: carts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      serviceAccountName: carts
      containers:
        - name: carts
          image: "public.ecr.aws/aws-containers/retail-store-sample-cart:1.6.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - configMapRef:
                name: carts
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 15
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
